[project]
name = "experimental"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.9.1",
    "fastapi[all]>=0.121.3",
    "lxml>=6.0.2",
    "mcp>=1.22.0",
    "playwright>=1.56.0",
]
